### ISSUE TITLE
Error al  mostrar el mapa

### ISSUE THREAD

**Issue by i62lotor** [geowe/gobuy#23]
La primera vez que consultas una categoría puedes ver la ubicación en el mapa. Las siguientes (tras dar a volver) sale en blanco.

**Comment by jmmluna** [comment]
Resuelto. Al cambiar de vista se perdía la referencia del mapa. El mapa solo se crea la primera vez en el listado de establecimientos, las siguientes visualizaciones se reutiliza la instancia. Se resuelve limpiando la instancia antes de volver al home, de esta forma, la siguiente vez sigue su ejecución normal.
