### ISSUE TITLE
Herramienta para buscar/filtrar establecimientos

### ISSUE THREAD

**Issue by geowe** [geowe/gobuy#26]
Se requiere una herramienta que permita buscar o filtrar los comercios desde el listado de establecimientos. Sería de interés que se pudiera buscar por nombre, dirección y contacto del establecimiento.

**Comment by jmmluna** [comment]
Resuelto. Ya se ha incorporado una herramienta de búsqueda que filtra a la vez que se escribe en el campo de texto. La búsqueda se realiza sobre los datos cargados en memoria, por lo que los filtros son muy rápidos.
