### ISSUE TITLE
error al intentar entrar en un establecimiento tras filtra

### ISSUE THREAD

**Issue by i62lotor** [geowe/gobuy#28]
Para reproducir el error:
1. Pulso entrar en un estableciminto
2. Hago una búsqueda y filtra mostrando otros establecimientos
3. Pulso en entrar en otro establecimiento

**Resultado Esperado:** Debería mostrar el aviso de que ya está en otro establecimiento
**Resultado:** No muestra aviso, y el botón se queda como en estado inconsistente.

Error en consola:
`TypeError: this.stablishments[a.default.getEntering(...)] is undefined`

**Comment by jmmluna** [comment]
Resuelto
