### ISSUE TITLE
Mostrar aforo del local

### ISSUE THREAD

**Issue by i62lotor** [geowe/gobuy#38]
Es interesante mostrar el aforo máximo de personas que  pueden estar en un establecimiento. Sobre todo para bares, terrazas, etc...

**Comment by i62lotor** [comment]
Se ha creado en base de datos la columna correspondiente, con valor por defecto 0.

**Comment by jmmluna** [comment]
Campo **aforo** disponible en la información del establecimiento en la versión 1.1.0
