### ISSUE TITLE
Mejorar formulario de alta

### ISSUE THREAD

**Issue by i62lotor** [geowe/gobuy#7]
Hacer el formulario responsive.
Incluir un mapa para ayudar a geolocalizar el establecimiento, a través de la dirección especificada (o manualmente)

**Comment by jmmluna** [comment]
El formulario ya se encuentra adaptado. la integración de un mapa en el formulario por ahora no se realiza. Se intenta obtener las coordenadas a partir de la dirección del formulario usando OSM Nominatim.
